import { ReactNode } from "react";
import type { Metadata } from "next";
import { roboto } from "../layout/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} bg-white gmarket dark:bg-[#cfd1dd]`}
      >
        {children}
      </body>
    </html>
  );
}
