"use client";

import { PropsWithChildren, ReactNode } from "react";
import { RecoilRoot } from "recoil";
import Header from "@/view/layout/Header";
import { roboto } from "@/view/layout/fonts";
import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <RecoilRoot>
        <ClientLayout>{children}</ClientLayout>
      </RecoilRoot>
    </html>
  );
}

const ClientLayout = (props: PropsWithChildren) => {
  return (
    <body className={`${roboto.className} gmarket bg-white dark:bg-[#cfd1dd]`}>
      <Header />
      <main className="h-[100vh] w-full pt-[3vh]">
        <section className="mx-auto my-0 h-[89vh] w-[96vw] overflow-hidden rounded bg-white py-[2%] dark:bg-opacity-30">
          {props.children}
        </section>
      </main>
    </body>
  );
};
